# Dockerfile.config

FROM ubuntu:latest

# Definindo variáveis de ambiente
ENV DEBIAN_FRONTEND=noninteractive

# Atualiza os pacotes e instala as dependências
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*

# Adiciona a chave GPG do Docker
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

# Adiciona o repositório do Docker
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# Instala o Docker
RUN apt-get update && apt-get install -y \
    docker-ce docker-ce-cli containerd.io \
    && rm -rf /var/lib/apt/lists/*

# Copia o script de configuração do SSH (ajustando o caminho)
COPY configs/configure_ssh.sh /usr/local/bin/configure_ssh.sh
RUN chmod +x /usr/local/bin/configure_ssh.sh

# Comando para executar o script ao iniciar o contêiner
CMD ["/usr/local/bin/configure_ssh.sh"]
